<script type="text/javascript">
    var $aff = jQuery.noConflict();
    // $aff(document).ready(function(){
    //      $aff( "body" ).addClass( "affiliate-page" );
    //      $aff( ".affiliate-page .messages" ).addClass( "col-lg-12 col-md-12 col-sm-12 col-xs-12" );
    //      $aff( ".affiliate-page .message" ).addClass( "col-lg-12 col-md-12 col-sm-12 col-xs-12" );
    // })
   
</script>
