<?php

$visibility = array(
  Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
  Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
  );

$_productCollection = Mage::getModel('catalog/product')->getCollection();
$_productCollection->addAttributeToSelect('*')
                   ->addFieldToFilter('visibility', $visibility) //showing just products visible in catalog or both search and catalog
                   ->addFinalPrice()
                   ->addAttributeToSort('created_at', 'desc') //in case we would like to sort products by price
                   ->getSelect()
                   // ->where('price_index.final_price < price_index.price')
                   ->limit(8) //we can specify how many products we want to show on this page
                   // ->order(new Zend_Db_Expr('RAND()')) //in case we would like to sort products randomly
                   ;

                   Mage::getModel('review/review')->appendSummary($_productCollection);

                   $_helper = $this->helper('catalog/output');
                   ?>

<?php $_collectionSize = $_productCollection->count() ?>
<?php $_columnCount = 4; ?>
<div class="page-title">
  <h2><a href="/novidades"><?php echo $this->__('Novidades') ?></a></h2>
</div>
<div class="category-products">
  <?php $i=0; foreach ($_productCollection as $_product): ?>
  <?php if ($i++%$_columnCount==0): ?>
    <ul class="products-grid">
    <?php endif ?>
    <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
          <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(299); ?>" width="100%" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
        <div class="item-bottom" style="position: relative;">
          <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
          <?php
            $groupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
            $storeId = Mage::app()->getStore()->getStoreId();
            $productid = $_product->getId();
            $like_product = Mage::getResourceModel('catalog/product')->getAttributeRawValue($productid,'experimental_prod', $storeId);
            if($like_product==0)
            {
              //if product is not experimental product then only show add to cart button.
              echo Mage_Catalog_Block_Product::getPriceHtml($_product, true);
              if($groupId > 1) :
          ?>
          <div class='preco_sugerido'>
            Preço sugerido para venda:
            <span><?php echo Mage::helper('core')->currency($_product->getMsrp(),true,false); ?></span>
          </div>
          <?php endif; ?>
          <div class="lastunits" style="position: absolute; top:-28px; left: 8px; background-color: #098d44; padding: 6px; color: #ffffff;">
            <?php
              $prodtype = $_product->getTypeID();
              $lastunit = Mage::getStoreConfig('stock_options/backend_group/last_unit_instructions');
              $qqty = 0;
              if($prodtype=='configurable')
              {
                $prod = $_product->load($prod_id);
                $conf = Mage::getModel('catalog/product_type_configurable')->setProduct($prod);
                $col = $conf->getUsedProductCollection()->addAttributeToSelect('*')->addFilterByRequiredOptions();
                $total_qty=0;
                foreach($col as $sprod){
                  $sprod=$_product->load($sprod->getId());
                  $prodnam = $sprod->getName();
                  $qty = intval(Mage::getModel('cataloginventory/stock_item')->loadByProduct($sprod)->getQty());
                  $qqty = $qty + $qqty;
                }
                if($qqty<=$lastunit)
                {
                  //echo "<p style='color:red;'>Last ".$qqty." unit(s) left.<p>";
                  echo "<span>ultimas unidades</span>";
                }
              }
              else
              {
                $pqty = intval(Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty());
                if($pqty<=$lastunit)
                {
                  //echo "<p style='color:red;'>Last ".$pqty." unit(s) left.</p>";
                  echo "<span>ultimas unidades</span>";
                }
              }
            ?>
          </div>
          <div class="actions">
            <?php if($_product->isSaleable()): ?>
              <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span>
                <?php echo $this->__('Add to Cart') ?> <img src="<?php echo $this->getSkinUrl('/images/cart-white.png'); ?>"/></span></span></button>
              <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
              <?php endif; ?>
            </div>
          </div>
        <?php }else{ ?>
          <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Buy Now'); ?></a>
          <?php } ?>
        </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
      <?php endif ?>
    <?php endforeach ?>
    <script type="text/javascript">
      $$('.price-box .old-price .price-label, .price-box .special-price .price-label').each(function(elm){
        elm.remove();
      });
      jQuery('span[id*="product-price-parcelado"]').each(function (i) {
        var ids = jQuery('[id="' + this.id + '"]');
        if (ids.length > 1) jQuery('[id="' + this.id + '"]:gt(1)').remove();
      });
      decorateGeneric($$('ul.products-grid'), ['odd','even','first','last']);
    </script>
  </div>
