<?php
  $roleId = Mage::getSingleton('customer/session')->getCustomerGroupId();
  $role = Mage::getSingleton('customer/group')->load($roleId)->getData('customer_group_code');
  $role = strtolower($role);
?>
<fieldset style="border: 1px solid #cccccc; padding: 15px; width: 50%;">
  <legend style="background-color: #ededed; color: #000; display: block !important; height: 20px; line-height: 18px; margin-top: 2px; padding: 10px;
    position: relative; visibility: visible; width: 214px;">Add products For Franchise Customers</legend>
  <form enctype="multipart/form-data" action="<?php echo $this->getUrl('*/*/getStock'); ?>" method="post">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
    <label style="width: 82px; float: left;">Order #:</label>
    <input type="text" id="franchise_order" name="franchise_order" value=""/><br/><br/>
    <label style="width: 82px; float: left;">Franchise id:</label>
    <input type="text" id="franchise_id" name="franchise_id" value=""/><br/><br/>
    <input type="submit" class="scalable submitin" value="Submit" style="border-width:1px; border-style:solid; border-color:#ed6502 #a04300 #a04300 #ed6502; padding:0 7px 1px 7px; background:#ffac47 url(<?php echo $this->getSkinUrl('images/btn_bg.gif'); ?>) repeat-x 0 100%; color:#fff; font:bold 12px arial, helvetica, sans-serif; cursor:pointer; text-align:center !important; white-space:nowrap;" />
  </form>
</fieldset>
