<?php
    $helper = Mage::helper('stock');
?>

<div class="dashboard">
    <div class="fieldset">
        <div class="page-title">
            <h1><?php echo $helper->__('Ajuda') ?></h1>
        </div>
        <div class="welcome-msg">
            <div>
                <strong><?php echo $helper->__('Atendimento online')?></strong>
            </div>
            <div>
                <p>
                <?php echo $helper->__('Possuimos um atendimento online das 10:00 até as 18:00 de
                segunda a sexta, clicque aqui e seja atendido ou deixe a sua mensagem.'); ?>
                </p>
            </div>
        </div>
        <div class="col2-set">
            <div class="sac">
                <div class="subtitler-sac">SAC</div>
                <div class="content-sac">
                    <div class="row-sac">
                        <div class="row-sac-title">Telefone:</div>
                        <div class="row-sac-content">11 9999-9999 - Atendimento das 09:00 até as 20:00</div>
                    </div>
                    <div class="row-sac">
                        <div class="row-sac-title">Email</div>
                        <div class="row-sac-content">planeta.futebol@sac.com.br</div>
                    </div>
                    <div class="row-sac">
                        <div class="row-sac-title">Endereço:</div>
                        <div class="row-sac-content">lalalla, 88, Brasil, São Paulo - SP</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>