<?php
	$helper = Mage::helper('stock');
	$roleId = Mage::getSingleton('customer/session')->getCustomerGroupId();

	if($roleId <= 1) {
		$_productCollection = $this->getCollection();
		$_helper = $this->helper('catalog/output');
	}

	$arrProductStockItem = $this->getData('productStockItem');

	$productStockItemTable = "";
	foreach ($arrProductStockItem as $item){

		$nameProductStockItem = $item['name'];
		$quantityProductStockItem = $item['quantity'];
		$descriptionQuantity = $helper->__('Quantidade: ');

		$productStockItemTable .= <<< "STOCK_ITEM"
			<tr>
				<td>$nameProductStockItem</td>
				<td>$descriptionQuantity</td>
				<td quantity="$quantityProductStockItem">$quantityProductStockItem</td>
			</tr>\n
STOCK_ITEM;

	}

	$arrProductMoreSold = $this->getData('productMoreSold');

	$productMoreSoldTable = "";
	foreach ($arrProductMoreSold as $item){

		$nameProductMoreSold = $item['name'];
		$quantityProductMoreSold = $item['quantity'];
		$descriptionQuantity = $helper->__('Quantidade: ');

		$productMoreSoldTable .= <<< "SOLD_ITEM"
			<tr>
				<td>$nameProductMoreSold</td>
				<td>$descriptionQuantity</td>
				<td>$quantityProductMoreSold</td>
			</tr>\n
SOLD_ITEM;

	}


	$arrProductMoreProfit = $this->getData('productMoreProfit');

	$productMoreProfitTable = "";
	foreach ($arrProductMoreProfit as $item){

		$nameProductMoreProfit = $item['name'];
		$valueProductMoreProfit = Mage::helper('core')->currency($item['profit']);

		$productMoreProfitTable .= <<< "PROFIT_ITEM"
			<tr>
				<td>$nameProductMoreProfit</td>
				<td>$valueProductMoreProfit</td>
			</tr>\n
PROFIT_ITEM;

	}


	$arrGenerateMoreCommission = $this->getData('generateMoreCommision');

	$generateMoreCommissionTable = "";
	foreach ($arrGenerateMoreCommission as $commission){

		$name = $commission['name'];
		$valueCommission = Mage::helper('core')->currency($commission['commission']);

		$generateMoreCommissionTable .= <<< "COMMISSION"
			<tr>
				<td>$name</td>
				<td>$valueCommission</td>
			</tr>\n
COMMISSION;

	}

?>

<div class="fieldset">
	<div class="page-title">
		<h1><?php echo $helper->__('Painel Franquia') ?></h1>
	</div>
	<div>
		<div>
			<strong><?php echo $helper->__('Olá, ') . $this->getData('nameCustomer') . '!'; ?></strong>
		</div>
		<div>
			<?php echo $helper->__('Aqui é possível ver um resumo das suas informações de estoque, comissões e vendas'); ?>
		</div>
	</div>
	<div class="comission-head">
		<div class="ch-fr-type">
			<strong>Tipo de franqueado: </strong>
			<?php echo $this->getData('nameFranchise'); ?>
		</div>
		<div class="ch-fr-cupom">
			<strong>Cupom varejo: </strong>
			<?php //echo $coupons['customer']; ?>
			<strong> | Cupom franquia: </strong>
			<?php //echo $coupons['franchise']; ?>
		</div>
	</div>
	<div class="overview">
		<form method="post" id="frsearch" enctype="multipart/form-data" action="">
			<input type="hidden" name="form_key"
				   value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
			<label for="franchise">
				<strong><?php echo $this->__('Desempenho de: '); ?></strong>
			</label>
			<select name="franchise" id="franchise">
				<option value="1" selected="selected"><?php echo $this->__('Hoje') ?></option>
				<option value="7"><?php echo $this->__('7 dias') ?></option>
				<option value="30"><?php echo $this->__('30 dias') ?></option>
				<option value="0"><?php echo $this->__('') ?></option>
			</select>
			<input type="submit" name="submit" id="submit" value="OK"/>
		</form>
		<div class="blocks">
			<div class="block">
				<div class="block-value">
					<span class="ov-value"><?php echo Mage::helper('core')->currency($this->getData('fullPotentialSales')); ?></span>
				</div>
				<div class="block-texts">
					<div>
						<?php echo $helper->__('Total potencial de venda'); ?>
					</div>
					<div>
						<?php echo $helper->__('(Valor do estoque atual)'); ?>
					</div>
				</div>
			</div>
			<div class="block">
				<div class="block-value">
					<span class="ov-value"><?php echo Mage::helper('core')->currency($this->getData('fullPurchases')); ?></span>
				</div>
				<div class="block-texts">
					<?php echo $helper->__('Total de compra'); ?>
				</div>
			</div>
			<div class="block">
				<div class="block-value">
					<span class="ov-value"><?php echo 'R$ 30.000,00' ?></span>
				</div>
				<div class="block-texts">
					<?php echo $helper->__('Total de crédito'); ?>
				</div>
			</div>
			<div class="block">
				<div class="block-value">
					<span class="ov-value"><?php echo Mage::helper('core')->currency($this->getData('fullSalesPrice')); ?></span>
				</div>
				<div class="block-texts">
					<?php echo $helper->__('Total de vendas'); ?>
				</div>
			</div>
			<div class="block">
				<div class="block-value">
					<span class="ov-value"><?php echo Mage::helper('core')->currency($this->getData('fullProfits')); ?></span>
				</div>
				<div class="block-texts">
					<?php echo $helper->__('Total de lucro'); ?>
				</div>
			</div>
		</div>
	</div>
	<div class="overview-sales-table">
		<div class="detais-sales-table stock-table">
			<div class="thearde-stock-table">
				<div class="title-details-sale-sable"><span><?php echo $helper->__('Estoque'); ?></span></div>
				<div><?php echo $helper->__('Produtos com menos estoque') ?></div>
			</div>
			<table>
				<tbody>
					<?php echo $productStockItemTable; ?>
				</tbody>
			</table>
		</div>
		<div class="detais-sales-table comissions-able">
			<div class="thearde-stock-table">
				<div class="title-details-sale-sable"><span><?php echo $helper->__('Comissões'); ?></span></div>
				<div><?php echo $helper->__('Maiores geradores de comissões') ?></div>
			</div>
			<table>
				<tbody>
					<?php echo $generateMoreCommissionTable; ?>
				</tbody>
			</table>
		</div>
		<div class="detais-sales-table sales-table">
			<div class="thearde-stock-table">
				<div class="title-details-sale-sable"><span><?php echo $helper->__('Vendas'); ?></span></div>
				<div><?php echo $helper->__('Produtos mais vendidos') ?></div>
			</div>
			<table>
				<tbody>
					<?php echo $productMoreSoldTable; ?>
				</tbody>
			</table>
		</div>
		<div class="detais-sales-table profit-table">
			<div class="thearde-stock-table">
				<div class="title-details-sale-sable"><span><?php echo $helper->__('Lucro'); ?></span></div>
				<div><?php echo $helper->__('Produtos que geram mais lucros') ?></div>
			</div>
			<table>
				<tbody>
					<?php echo $productMoreProfitTable;	?>
				</tbody>
			</table>
		</div>
	</div>
</div>
