<?php
  $roleId = Mage::getSingleton('customer/session')->getCustomerGroupId();
  $role = Mage::getSingleton('customer/group')->load($roleId)->getData('customer_group_code');
  $role = strtolower($role);

  $helper= Mage::helper('stock');
  if($role=='franchise'){
?>
  <div class="fieldset">
    <h2 class="legend"><?php echo $helper->__('Product List') ?></h2>
    <div class="productlist">
      <p style="display: none;">
        <form method="post" enctype="multipart/form-data">
          <input type="text" name="searchfr" id="searchfr"/>
          <input type="submit" name="submit" id="submit"/>
        </form>
      </p>
      <table>
        <thead>
          <th>
            <td>Product Name</td>
            <td>Quantity</td>
            <td>Purchased at</td>
            <td>Price</td>
            <td>Action</td>
          </th>
        </thead>
        <tbody>
        <?php
          $userid = Mage::getSingleton('customer/session')->getCustomer()->getId();
          $querydata = Mage::getModel('stock/product')->getCollection()
              ->addFieldToFilter('userid', array('eq' => $userid))
              ->addFieldToFilter('status', array('neq' => 2))
              ->setOrder('stockproductid');
          $rowdata=array();

          foreach ($querydata as  $value) {
            $qty = (int)Mage::getModel('cataloginventory/stock_item')
             ->loadByProduct($value->getStockproductid())->getQty();

            if($qty){
              $rowdata[] = $value->getStockproductid();
            }
          }

          $collection = Mage::getModel('catalog/product')->getCollection();
          $collection->addAttributeToSelect('*');

          if(array_key_exists('c', $_GET)){
            $collection->addCategoryFilter($cate);
          }

          $collection->addAttributeToFilter('entity_id', array('in' => $rowdata));

          foreach($collection as $products) {
            $productMediaConfig = Mage::getModel('catalog/product_media_config');
        ?>
          <tr>
            <td><?php echo $products->getName(); ?></td>
            <td><?php echo $products->getPrice(); ?></td>
            <td><?php echo Mage::helper('core')->currency($products->getFinalPrice(),true,false); ?></td>
            <td><?php echo Mage::helper('core')->currency($products->getPrice(),true,false); ?></td>
          </tr>
        <?php
          }
        ?>
        </tbody>
      </table>
    </div>
  </div>
<?php
  }else{
    echo $helper->__("<h2 class='wk_new_msg'>To become a Franchise contact admin...</h2>");
  }
?>
