<?php
  $roleId = Mage::getSingleton('customer/session')->getCustomerGroupId();
  $magentoCurrentUrl = Mage::helper('core/url')->getCurrentUrl();
  $helper=Mage::helper('stock');

  if($roleId>1) {
?>
<div class="block block-account">
  <div class="block-title">
    <strong><span><?php echo $helper->__('Franquia') ?></span></strong>
  </div>
  <div class="block-content">
    <ul class="wk_cont_ul">
      <li <?php echo strpos($magentoCurrentUrl,'myproductslist')? "class=current":"";?>>
      <?php if(strpos($magentoCurrentUrl,'myproductslist')){ ?>
        <strong><?php echo $helper->__('Meu Estoque') ?></strong>
      <?php } else { ?>
        <a href="<?php echo $this->getUrl('stock/stockaccount/myproductslist'); ?>">
          <?php echo $helper->__('Meu Estoque') ?>
        </a>
      <?php } ?>
      </li>
      <li  <?php echo strpos($magentoCurrentUrl,'saleperpartner')? "class=current":"";?>>
      <?php if(strpos($magentoCurrentUrl,'saleperpartner')){ ?>
        <strong><?php echo $helper->__('Relatórios') ?></strong>
      <?php } else { ?>
        <a href="<?php echo $this->getUrl('stock/stockaccount/saleperpartner'); ?>">
          <?php echo $helper->__('Relatórios') ?>
        </a>
      <?php } ?>
      </li>

      <li  <?php echo strpos($magentoCurrentUrl,'listTransaction')? "class=current":"";?>>
      <?php if(strpos($magentoCurrentUrl,'listTransaction')){ ?>
        <strong><?php echo $helper->__('Comissões') ?></strong>
      <?php } else { ?>
        <a href="<?php echo $this->getUrl('affiliateplus/index/listTransaction'); ?>">
          <?php echo $helper->__('Comissões') ?>
        </a>
      <?php } ?>
      </li>

      <li  <?php echo strpos($magentoCurrentUrl,'affiliateplus/refer/index')? "class=current":"";?>>
      <?php if(strpos($magentoCurrentUrl,'affiliateplus/refer/index')){ ?>
        <strong><?php echo $helper->__('Refer Friends') ?></strong>
      <?php } else { ?>
        <a href="<?php echo $this->getUrl('affiliateplus/refer/index'); ?>">
          <?php echo $helper->__('Refer Friends') ?>
        </a>
      <?php } ?>
      </li>

      <li  <?php echo strpos($magentoCurrentUrl,'affiliateplusstatisticfrontend/statistic/index')? "class=current":"";?>>
      <?php if(strpos($magentoCurrentUrl,'affiliateplusstatisticfrontend/statistic/index')){ ?>
        <strong><?php echo $helper->__('Relatório de Comissões') ?></strong>
      <?php } else { ?>
        <a href="<?php echo $this->getUrl('affiliateplusstatisticfrontend/statistic/index'); ?>">
          <?php echo $helper->__('Relatório de Comissões') ?>
        </a>
      <?php } ?>
      </li>

      <li  <?php echo strpos($magentoCurrentUrl,'affiliatepluscoupon/index/index')? "class=current":"";?>>
      <?php if(strpos($magentoCurrentUrl,'affiliatepluscoupon/index/index')){ ?>
        <strong><?php echo $helper->__('Cupons') ?></strong>
      <?php } else { ?>
        <a href="<?php echo $this->getUrl('affiliatepluscoupon/index/index'); ?>">
          <?php echo $helper->__('Cupons') ?>
        </a>
      <?php } ?>
      </li>

    </ul>
  </div>
</div>
<?php } ?>
