<?php
  $roleId = Mage::getSingleton('customer/session')->getCustomerGroupId();
  $magentoCurrentUrl = Mage::helper('core/url')->getCurrentUrl();
  $helper=Mage::helper('stock');

  if($roleId>1) {
?>
<div class="block block-account">
  <div class="block-title">
    <strong><span><?php echo $helper->__('Franquia') ?></span></strong>
  </div>
  <div class="block-content">
    <ul class="wk_cont_ul">
<!--
      <li <?php //echo strpos($magentoCurrentUrl,'dashboard')? "class=current":"";?>>
      <?php //if(strpos($magentoCurrentUrl,'dashboard')) { ?>
        <strong><?php //echo $helper->__('Painel') ?></strong>
      <?php //} else { ?>
        <a href="<?php //echo $this->getUrl('stock/stockaccount/dashboard'); ?>">
          <?php //echo $helper->__('Painel') ?>
        </a>
      <?php //} ?>
      </li> -->
      <li <?php echo strpos($magentoCurrentUrl,'myproductslist')? "class=current":"";?>>
      <?php if(strpos($magentoCurrentUrl,'myproductslist')){ ?>
        <strong><?php echo $helper->__('Meu Estoque') ?></strong>
      <?php } else { ?>
        <a href="<?php echo $this->getUrl('stock/stockaccount/myproductslist'); ?>">
          <?php echo $helper->__('Meu Estoque') ?>
        </a>
      <?php } ?>
      </li>
      <li  <?php echo strpos($magentoCurrentUrl,'saleperpartner')? "class=current":"";?>>
      <?php if(strpos($magentoCurrentUrl,'saleperpartner')){ ?>
        <strong><?php echo $helper->__('Relatórios') ?></strong>
      <?php } else { ?>
        <a href="<?php echo $this->getUrl('stock/stockaccount/saleperpartner'); ?>">
          <?php echo $helper->__('Relatórios') ?>
        </a>
      <?php } ?>
      </li>

      <li  <?php echo strpos($magentoCurrentUrl,'commission')? "class=current":"";?>>
      <?php if(strpos($magentoCurrentUrl,'commission')){ ?>
        <strong><?php echo $helper->__('Comissões') ?></strong>
      <?php } else { ?>
        <a href="<?php echo $this->getUrl('stock/stockaccount/commission'); ?>">
          <?php echo $helper->__('Comissões') ?>
        </a>
      <?php } ?>
      </li>

      <li  <?php echo strpos($magentoCurrentUrl,'affiliatepluscoupon/index/index')? "class=current":"";?>>
      <?php if(strpos($magentoCurrentUrl,'affiliatepluscoupon/index/index')){ ?>
        <strong><?php echo $helper->__('Cupons') ?></strong>
      <?php } else { ?>
        <a href="<?php echo $this->getUrl('affiliatepluscoupon/index/index'); ?>">
          <?php echo $helper->__('Cupons') ?>
        </a>
      <?php } ?>
      </li>

    </ul>
  </div>
</div>
<?php } ?>
