<?php
/**
 * Sales transaction history template
 */
?>
<?php
$store_id = Mage::app()->getStore()->getStoreId();
$check_responsvie = Mage::getStoreConfig('affiliateplus/style_config/responsive_enable', $store_id);
 if($check_responsvie)
     $class_name = 'col-lg-9 col-md-9 col-sm-12 col-xs-12';
 else
     $class_name = 'col-lg-9 col-md-9 col-sm-9 col-xs-9';
?>

<div class="fieldset <?php echo $class_name; ?>">
<div class="page-title">
  <h2><?php echo $this->__('Relatórios') ?></h2>
</div>
<div class="saleswrap"> <!--fieldset-->
    <ul class="tabrl">
      <li class="tabi firsttab tabs" tabid="salesreportlist"><p><a href="<?php echo $this->getUrl('stock/stockaccount/saleperpartner'); ?>">Vendas</a></p></li>
      <li class="tabi tabs" tabid="financialgraph"><p><a href="<?php echo $this->getUrl('stock/stockaccount/saleperpartner'); ?>">Financeiro</a></p></li>
      <li class="tabi tabs active lasttab" tabid="commissionslist"><p>Comissões</p></li>
    </ul>
    <div style="clear: both;"></div>
  </div>
<?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php // echo $this->getChildHtml('payment_miniform') ?>
<?php //echo $this->getChildHtml('sales_statistic') ?>

<?php echo $this->getTransactionHtml() ?>
</div>
