<div class="homepage">

	<div id="slider">
		<div class="slidercontrolwr-left">
			<div class="slidercontrol">
				<a href="#" class="aprev" title="Previous" onClick="my_glider.previous();return false;">Previous</a>
			</div>
		</div>
		<div class="slidercontrolwr-right">
			<div class="slidercontrol">
				<a href="#" class="anext" title="Next" onClick="my_glider.next();return false">next</a>
			</div>
		</div>
	    <div class="scroller">
	    	<div class="content">
				<div class="section" id="section1">
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('slider-home-1')->toHtml() ?>
	    		</div>
          <?php if ($this->getLayout()->createBlock('cms/block')->setBlockId('slider-home-2')->toHtml() !== ''): ?>
	    		<div class="section" id="section2">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('slider-home-2')->toHtml() ?>
	    		</div>
        <?php endif; ?>
	    	</div>
	    </div>
	</div>
	<script src="<?php echo $this->getSkinUrl('js/') ?>glider.js" type="text/javascript"></script>
	<script type="text/javascript" charset="utf-8">
		var my_glider = new Glider('slider', {duration:0.5, autoGlide: true, frequency: 4, initialSection: 'section1'});
	</script>

	<div class="home-right">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-topbox')->toHtml() ?>
	</div>
	<div class="clearer"></div>

	<div class="advantages">
		<ul>
			<li><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('advantages-1')->toHtml() ?></li>
			<li><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('advantages-2')->toHtml() ?></li>
			<li><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('advantages-3')->toHtml() ?></li>
			<li><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('advantages-4')->toHtml() ?></li>
		</ul>
	</div>
	<div class="clearer"></div>
</div>